name: GitLab Deployment Image

on:
  pull_request:
    branches:
      - master
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        docker login --username=arunalakmal --password=${{ secrets.TCDockerCred }}
        docker image build -t arunalakmal/tc-terraform-ansible-aws:v1.0.2 .
        docker push arunalakmal/tc-terraform-ansible-aws:v1.0.2
